
# Analytik -----------------------------------------------------------

df_analytik <- df_import_analytik %>%
  filter(
    str_detect(probe, "(?i)^GT") | probenart == "inokulum" | projekt == "inokulum"
  ) %>%
  summarise(
    across(
      where(is.numeric), 
      ~ mean(.x, na.rm = TRUE))
    ) %>%
  mutate(
    probenart = "inokulum",
    probe = "blind_mean",
    analytik_nr = "blind_mean") %>%
  bind_rows(df_import_analytik,.) %>%
  fill(gaertest, .direction = "down") 

# Proben ------------------------------------------------------------------

df_proben <- df_import_samples %>%
  left_join(
    .,
    select(
      df_analytik, analytik_nr, ts_perc_fm, ots_perc_ts
    ),
    join_by(analytik_nr)
  ) %>%
  mutate(
    otm_k_fm = ts_perc_fm * ots_perc_ts / 100
  ) %>%
  mutate(
    einwaage_in_g_odm = einwaage_in_g_fm * ts_perc_fm /100 * ots_perc_ts / 100,
    p_i = if_else(
      str_detect(analytik_nr, "blind_mean"),
      NA,
      einwaage_in_g_odm / mean(einwaage_in_g_odm[analytik_nr == "blind_mean"])
    ),
    .after = otm_k_fm)

# combined ---------------------------------------------------------

df_import_w1_6 <- df_proben %>%
  select(
    projekt,
    wanne, 
    platz, 
    probe, 
    messplatz, 
    d_gasmaus_cm,
    nullpunkt_cm,
    analytik_nr,
    einwaage_in_g_fm,
    otm_k_fm) %>%
  right_join(
    .,
    df_import_gaswerte,
    join_by(wanne, platz)
  ) %>%
  drop_na(probe) 

# Gaswerte---------------------------------------------------------------------

## Normfaktor --------------------------------------------------------------

df_w1_6 <- df_import_w1_6 %>%
  filter(!messplatz %in% bad_channels) %>%
  group_by(messplatz) %>% 
  mutate(
    normfaktor = (druck - (-4.3965+9.7962 * exp(0.0521 * temp)))*273.15/
                 (1013.25 * (273.15 + temp))
         ) %>%

## Volumen BG --------------------------------------------------------------

  mutate(
    h_2   = (hoehe_mm / 10) - nullpunkt_cm,
    h_1   = (dplyr::lag(hoehe_mm) / 10) - nullpunkt_cm,
    A_zyl = pi * (d_gasmaus_cm / 2)^2
    ) %>%
  mutate(
    vol_norm = if_else(
      is.na(dplyr::lag(ch4_perc)),
      h_2 * A_zyl * normfaktor - h_1 * dplyr::lag(A_zyl) * dplyr::lag(normfaktor),
      h_2 * A_zyl * normfaktor
      )
    ) %>%
  select(-c(h_2, h_1, A_zyl)) %>%

# replace na generated by the lag function (day 1)
  mutate(
    vol_norm = replace_na(
      vol_norm, 0
      )
    ) %>%

## CH4 korrigiert -------------------------------------------------

  mutate(
    methane_perc = if_else(
      ch4_perc > 0 & co2_perc > 0,
      ch4_perc / (ch4_perc + co2_perc) * 100,  # vermeiden durch 0 zu dividieren
      NA
      )
    ) %>%
  ungroup(.) 

## Blind MW pro Wanne ------------------------------------------------------
df_w1_6_blind <- df_w1_6 %>%
  filter(str_detect(probe, "blind_w")) %>%
  group_by(wanne, datum, zeit) %>%
  summarise(
    blind_mean = mean(vol_norm)
    ) %>%
  ungroup() 

df_w1_6 <- df_w1_6 %>%
  left_join(
    .,
    df_w1_6_blind,
    join_by(wanne, datum, zeit)
    )%>% 
  mutate(
    vol_norm_net = if_else(
      str_detect(probe, "blind_w"),
      vol_norm,
      vol_norm - blind_mean
    )
  ) 

## Volumen CH4 -------------------------------------------------------------

df_w1_6_methan <- df_w1_6 %>%
  group_by(messplatz) %>%
  mutate(
    vol_norm_net_cum = cumsum(
      vol_norm_net
      )
    ) %>%
  filter(!is.na(methane_perc)) %>%
 # na.omit() %>%
  mutate(
    vol_norm_net_methan = (vol_norm_net_cum - dplyr::lag(vol_norm_net_cum, default = 0)) * methane_perc / 100
    ) %>%
  
  select(messplatz, datum, zeit, vol_norm_net_methan) 

df_w1_6 <- df_w1_6 %>%
  left_join(
    .,
    df_w1_6_methan,
    join_by(messplatz, datum, zeit)
    ) %>%
            
  ungroup() %>%
  arrange(wanne, platz, datum, zeit) %>%
  # create variable run_time for later usage for calculating  "abbruchkriterium" where exact time span is needed
  group_by(wanne, platz) %>%
  mutate(
    run_time = cumsum(
      as.numeric(difftime(zeit, dplyr::lag(zeit, default = first(zeit)), units = "days"))
    ),
    .after = zeit
  ) %>%
  ungroup()

## Tagessummen BG,CH4-----------------------------------------------

df_w1_6_daily_interim <- df_w1_6 %>%
  group_by(projekt, wanne, platz, messplatz, analytik_nr, probe, einwaage_in_g_fm, otm_k_fm, datum) %>%
  summarise(
    vol_norm            = sum(vol_norm),
    blind_mean          = sum(blind_mean),
    vol_norm_net        = sum(vol_norm_net),
    vol_norm_net_methan = if_else(
      all(is.na(vol_norm_net_methan)),
      NA,
      sum(vol_norm_net_methan, na.rm = TRUE)
      )
    ) %>%
mutate(
    day = cumsum(
      as.numeric(datum - dplyr::lag(datum, default = first(datum)))
      ),
    .before = vol_norm
    ) %>%
  mutate(
    vol_norm_net_cum        = cumsum(vol_norm_net)
    ) %>%
  mutate(
    vol_norm_net_methan_cum = replace(
      vol_norm_net_methan, 
      is.na(vol_norm_net_methan), 
      0) %>%
      cumsum() %>%
      replace(is.na(vol_norm_net_methan), NA)
    ) %>%
  ungroup() %>%
  mutate(vol_norm_net_methan_cum = if_else(
    day == 0,
    0,
    vol_norm_net_methan_cum)
    ) %>%
  mutate(
    methane_perc = if_else(
      day == 0,
      0,
      vol_norm_net_methan_cum / vol_norm_net_cum * 100
      )
  ) %>%
  select(
    -any_of(
      c("blind_mean", "vol_norm")
      )
       ) %>%
  ungroup() 
       
# Abbruchkriterium---------------------------------------------------------------

## Probe <= 0,5% ---------------------------------------
df_abbruch <- df_w1_6_daily_interim %>%
  select(wanne, platz, messplatz, probe, datum, day, vol_norm_net, vol_norm_net_cum) %>%
  filter(!str_detect(probe, "blind_w")) %>% 
  left_join(
    .,
    select(df_w1_6, messplatz, datum, run_time),
    join_by(messplatz, datum),
    multiple = "last"
  ) %>%
  group_by(messplatz) %>%
  mutate(
    vol_perc = if_else(
      day == 0, 
      100, 
      vol_norm_net / vol_norm_net_cum / (run_time - dplyr::lag(run_time, default = 0)) * 100
    ) 
  ) %>%
  view()

df_abbruch_wide <- df_abbruch %>%
  arrange(wanne, platz) %>%
  
  pivot_wider(
    id_cols = c("datum", "day"),
    names_from = messplatz,
    values_from = vol_perc
  ) 

df_condition <- df_abbruch %>%
  mutate(
    condition_probe = vol_perc <= 0.5
  ) %>%
    
## wdh <=0.5 /3d---------------------------------------------------------------
  #df_condition <- df_condition %>%
    group_by(probe,day) %>%
    summarise(
      condition_variant = all(condition_probe)) %>%
    arrange(probe, day) %>%
    group_by(probe) %>%
  
  mutate(
   condition =  if_else(
     #condition_variant == TRUE &
     dplyr::lag(condition_variant) == TRUE &
     dplyr::lag(condition_variant, n = 2) == TRUE &
     dplyr::lag(condition_variant, n = 3) == TRUE &
     day > 25,
     FALSE,
     TRUE
     )
   ) %>%
  #sobald Kriterium erreicht ist, alle Folgewerte verwerfen
  mutate(
    condition = if_else(
      dplyr::lag(condition, default = TRUE) == FALSE,
      FALSE,
      condition
    )
  ) %>%
  ungroup() 

df_condition_wide <- df_condition %>%
  pivot_wider(
    id_cols = day,
    names_from = probe,
    values_from = condition
  ) 


# Ergebnisse -----------------------------------------------------------------

## Messwerte nach Kriterium ------------------------------------------------

df_w1_6_daily <- df_w1_6_daily_interim %>%
  left_join(
    .,
    df_condition,
    join_by(probe, day)
  ) %>%
  mutate(
    condition = if_else(
      is.na(condition)|condition == 1,
      TRUE,
      FALSE
    )
  ) %>%
  filter(condition == TRUE) %>%
  select(-c(condition, condition_variant)) 

## Gültigkeit der Messungen nach VDI4630-----------------------------------

test_validity <- df_w1_6_daily %>%
  group_by(projekt, messplatz,probe) %>%
  summarise(
    vol_norm_net_cum = last(
      vol_norm_net_cum
    )
  ) %>%
  left_join(
    .,
    select(df_import_samples, any_of(c("messplatz", "wanne","variante"))),
    join_by(messplatz)) %>%
  group_by(projekt, probe,wanne) %>%
  
  # Generate all combinations of the elements of x taken m at a time.
  # If x is a positive integer, returns all combinations of the elements of seq(x) taken m at a time.
  # If argument FUN is not NULL, applies a function given by the argument to each point.

  reframe(
    pruefglied = list(
      if (n() > 1) combn(messplatz, 2, paste0, collapse = '-') 
      else messplatz),
    mean_BG   = list(
      if (n() > 1) combn(vol_norm_net_cum, 2, mean) 
      else vol_norm_net_cum),
    diff_BG   = list(
      if (n() > 1) abs(combn(vol_norm_net_cum, 2, diff)) 
      else NA)
  ) %>%
  drop_na(.) %>%
  unnest(cols = c(pruefglied, mean_BG, diff_BG)) %>%
  mutate(
    diff_mean_perc = diff_BG / mean_BG * 100
  )

# case_when(
#   diff_BG <= mean_BG * 0.05 ~ "<5%" ,
#   diff_BG > mean_BG * 0.05 & diff_BG <= mean_BG * 0.1 ~ "<10%" ,
#   diff_BG > mean_BG * 0.01 & diff_BG <= mean_BG * 0.15 ~ "<15%" ,
#   diff_BG > mean_BG * 0.15 & diff_BG <= mean_BG * 0.2 ~ "<20%",
#   Else = ">20%")

## Zusammenfassung ---------------------------------------------------------

df_results_individuals_daily <- df_w1_6_daily %>%
  mutate(
    # biogas_yield_fm   = vol_norm_net_cum / einwaage_in_g_fm,
    # methane_yield_fm  = vol_norm_net_methan_cum / einwaage_in_g_fm,
    biogas_yield_odm  = vol_norm_net_cum / (einwaage_in_g_fm * otm_k_fm / 100),
    methane_yield_odm = vol_norm_net_methan_cum / (einwaage_in_g_fm * otm_k_fm / 100)
  ) %>%
  select(
    -any_of(
      c("einwaage_in_g_fm", "otm_k_fm", "vol_norm_net", "vol_norm_net_methan", "vol_norm_net_cum", "vol_norm_net_methan_cum")
    )
  ) 
  

